// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNrrvwxqjiuz9KaKZbvyxsD9O9GA80jc4',
    appId: '1:1076024540059:web:034934f8ca71e8d69b7f3e',
    messagingSenderId: '1076024540059',
    projectId: 'flutter-mynotes-learning',
    authDomain: 'flutter-mynotes-learning.firebaseapp.com',
    storageBucket: 'flutter-mynotes-learning.appspot.com',
    measurementId: 'G-0DK15QJNRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rqEUhGJUr3mgq_R0gRNVwAqI2Yryg74',
    appId: '1:1076024540059:android:efa16d98613a1b609b7f3e',
    messagingSenderId: '1076024540059',
    projectId: 'flutter-mynotes-learning',
    storageBucket: 'flutter-mynotes-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6yw7YtWCTUz_7QB8Bh6qX3FJET0u80o',
    appId: '1:1076024540059:ios:25c87ef28d76051a9b7f3e',
    messagingSenderId: '1076024540059',
    projectId: 'flutter-mynotes-learning',
    storageBucket: 'flutter-mynotes-learning.appspot.com',
    iosBundleId: 'com.huseyinyeldan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6yw7YtWCTUz_7QB8Bh6qX3FJET0u80o',
    appId: '1:1076024540059:ios:aaacf5e7cffa328d9b7f3e',
    messagingSenderId: '1076024540059',
    projectId: 'flutter-mynotes-learning',
    storageBucket: 'flutter-mynotes-learning.appspot.com',
    iosBundleId: 'com.huseyinyeldan.mynotes.RunnerTests',
  );
}
